---
title: "Introduction to ImmuneSpaceR, BioC 2016"
date: "`r Sys.Date()`"
output: html_document
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Introduction to ImmuneSpaceR}
---


```{r}
# Connections
library(ImmuneSpaceR)
con <- CreateConnection("SDY269")

# Datasets
hai <- con$getDataset("hai")
hai <- con$getDataset("hai", original_view = TRUE)
library(Rlabkey)
virus_filter <- makeFilter(c("virus", "CONTAINS", "H1N1"))
hai_f <- con$getDataset("hai", colFilter = virus_filter)
virus_filter2 <- makeFilter(c("virus", "EQUAL", "A/Brisbane/59/2007 (H1N1)"))
hai_f <- con$getDataset("hai", colFilter = virus_filter2)

analyte_filter <- makeFilter(c("Analyte", "EQUAL", "IFNg"), c("Study time collected", "IN", "0;7"))
elisa <- con$getDataset("elisa", colFilter = analyte_filter)


# Cross assay
analyte_filter2 <- makeFilter(c("Analyte", "EQUAL", "IgG"), c("Study time collected", "EQUAL", "7"))
elispot <- con$getDataset("elispot", colFilter = analyte_filter2, reload = TRUE)
elispot <- elispot[, elispot_response := spot_number_reported + 1]
elispot <- elispot[, list(participant_id, elispot_response)]

fcs <- con$getDataset("fcs_analyzed_result")
fcs <- fcs[, fcs_response := (as.double(population_cell_number) + 1) / as.double(base_parent_population)][study_time_collected == 7]
res <- merge(elispot, hai, by = "participant_id")

ggplot(res, aes(x = as.double(hai_response), y = elispot_response, color = cohort)) +
  geom_point() + scale_x_continuous(trans = "log2") + scale_y_log10() + geom_smooth(method = "lm") +
  xlab("HAI fold") + ylab("Influenza specific cells\n (per 10^6 PBMCs)") + theme_IS()



# QP
con$quick_plot("hai", normalize = FALSE)
con$quick_plot("hai", filter = virus_filter2, normalize = FALSE, color = "Age", shape = "Gender")

# Expression
con$listDatasets(which = "expression")
em <- con$getGEMatrix(x = "TIV_2008")
em <- con$getGEMatrix(cohort = "TIV Group 2008")
em <- con$getGEMatrix("TIV_2008", summary = TRUE)
library(Biobase)
head(pData(em))

ems <- con$getGEMatrix(c("TIV_2008", "LAIV_2008"), summary = TRUE) #Summary usually better for cross cohort (& cross study)


# Cross study
all <- CreateConnection("")
all$listDatasets()

ahai <- all$getDataset("hai")
ahai <- all$getDataset("hai", colFilter = virus_filter3)
virus_filter3 <- makeFilter(c("cohort", "contains", "TIV"))
all$quick_plot("hai", filter = virus_filter3, normalize = TRUE)


## EM cross-study
csem <- all$getGEMatrix(c("SDY63_young_PBMC_year1", "SDY404_young_PBMC_year2"), summary = TRUE)
```





```{r}


fc_hai <- hai[, list(arm_accession, study_time_collected, study_time_collected_unit,
                     HAI = value_reported[study_time_collected == 28] /
                       mean(value_reported[study_time_collected == 0])), by = "participant_id,virus"]
fc_hai <- fc_hai[, list(HAI = log2(max(HAI))), by = "participant_id"]
#fc_elisa <- elisa[, IFNg := value_reported[study_time_collected == 7] / value_reported[study_time_collected == 0], by = "participant_id,analyte"][study_time_collected == 7 & !is.na(IFNg)]

fc_elisa <- elisa[, value := value_reported[study_time_collected == 7] / value_reported[study_time_collected == 0], by = "participant_id,analyte"][study_time_collected == 7 & !is.na(value)]
res <- merge(fc_hai, fc_elisa, by = "participant_id")

ggplot(res, aes(x = HAI, y = value)) + geom_point() + theme_IS() + geom_smooth(method = "lm") + facet_wrap(~analyte, scales = "free") + ggtitle("Fold change of day 7 ELISA vs. HAI reponse at peak Immunogenicity")
```
